AlanUmracoTest/Models/ChequeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AlanUmracoTest.Models
{
    public class ChequeModel
    {
        public string Name { get; set; }
        public double Amount { get; set; }
        public DateTime Date { get; set; }
        public string DetailsLink { get; set; }

        public ChequeModel(string name, double amount, DateTime date, string detailsLink)
        {
            Name = name;
            Amount = amount;
            Date = date;
            DetailsLink = detailsLink;
        }

    }
}

AlanUmracoTest/Controllers/ChequeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using AlanUmracoTest.Models;

namespace AlanUmracoTest.Controllers
{
    public class ChequeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Cheque/";

        /// <summary>
        /// Renders the cheque list partial
        /// </summary>
        /// <returns>Partial view with Cheque model</returns>
        /// 
        public ActionResult RenderChequeList()
        {
            List<ChequeModel> model = new List<ChequeModel>();
            IPublishedContent ChequeListPage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "chequeList").FirstOrDefault();

            foreach (IPublishedContent item in ChequeListPage.Children.OrderByDescending(x => x.GetPropertyValue<string>("chequeDate")))
            {
                string ChequeName = item.Name;

                double ChequeAmount = 0;
                double.TryParse(item.GetPropertyValue<string>("chequeAmount"), out ChequeAmount);

                DateTime chequeDate;
                DateTime.TryParse(item.GetPropertyValue<string>("chequeDate"), out chequeDate);

                string DetailsLink = item.Url;

                model.Add(new ChequeModel(ChequeName, ChequeAmount, chequeDate, DetailsLink));
            }

            return PartialView(PARTIAL_VIEW_FOLDER + "_ChequeList.cshtml", model);
        }

        /// <summary>
        /// Renders the cheque details partial
        /// </summary>
        /// <returns>Partial view</returns>
        /// 
        public ActionResult RenderChequeDetails()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_CheckDetails.cshtml");
        }
    }
}

AlanUmracoTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Web;
using Umbraco.Core.Models;

namespace AlanUmracoTest.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Home/";

        /// <summary>
        /// Renders the intro partial
        /// </summary>
        /// <returns>Partial view</returns>
        /// 
        public ActionResult RenderIntro()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Intro.cshtml");
        }
    }
}

AlanUmracoTest/Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;
//using System.Runtime.Caching;

namespace AlanUmracoTest.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";

        /// <summary>
        /// Renders the header partial
        /// </summary>
        /// <returns>Partial view</returns>
        /// 
        public ActionResult RenderHeader()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Header.cshtml");
        }

        /// <summary>
        /// Renders the footer partial
        /// </summary>
        /// <returns>Partial view</returns>
        /// 
        public ActionResult RenderFooter()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Footer.cshtml");
        }

    }
}

AlanUmracoTest/Views/ChequeDetails.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}
<div class="details-maindiv">
    <div class="details-header">
        <h1>Cheque Details</h1>
    </div>
    @{ Html.RenderAction("RenderChequeDetails", "Cheque");}
</div>

AlanUmracoTest/Views/ChequeList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

<div class="details-header">
    <h1>Cheque List</h1>
</div>
@{ Html.RenderAction("RenderChequeList", "Cheque");}

AlanUmracoTest/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@{Html.RenderAction("RenderIntro", "Home"); }

AlanUmracoTest/Views/Partials/Cheque/_CheckDetails.cshtml
@inherits UmbracoTemplatePage
@using AlanUmracoTest.Helpers

<div class="row">
    <table>
        <tr>
            <td>
                Name
            </td>
            <td>
                @Umbraco.AssignedContentItem.Name
            </td>
        </tr>
        <tr>
            <td>
                Date
            </td>
            <td>
                @ChequeHelper.DisplayDateShortFormat(@Umbraco.AssignedContentItem.GetPropertyValue("chequeDate").ToString())
           </td>
        </tr>
        <tr>
            <td>
                Amount
            </td>
            <td>
                @ChequeHelper.DisplayAmount(@Umbraco.AssignedContentItem.GetPropertyValue("chequeAmount").ToString())
            </td>
        </tr>
        <tr>
            <td>
                Pay
            </td>
            <td>
                @ChequeHelper.DisplayAmountInWordsFormat(@Umbraco.AssignedContentItem.GetPropertyValue("chequeAmount").ToString())                
            </td>
        </tr>
    </table>
</div>
<div class="details-footer">
    <a href="/chequelist/">Back to Cheque List</a>
</div>

AlanUmracoTest/Views/Partials/Cheque/_ChequeList.cshtml
@model List<ChequeModel>
@using AlanUmracoTest.Models
@using AlanUmracoTest.Helpers


<div class="blog-inner">
    <table class="table-fill">
        <thead>
            <tr>
                <th class="text-center">Name</th>
                <th class="text-center">Amount</th>
                <th class="text-center">Date</th>
                <th class="text-center">Details</th>
            </tr>
        </thead>
        <tbody class="table-hover">

            @foreach (ChequeModel cheque in Model)
            {

                @RenderChequeList(cheque);
            }
        </tbody>
    </table>

</div>

@helper RenderChequeList(ChequeModel item)
        {
    <tr>
        <td class="text-left">@item.Name</td>            
        <td class="text-left">
            @ChequeHelper.DisplayAmount(@item.Amount.ToString())
        </td>
        <td class="text-center">
            @ChequeHelper.DisplayDateShortFormat(@item.Date.ToString())
        </td>
        <td class="text-center">
            <a href="@item.DetailsLink">Details</a>
        </td>
    </tr>

}

AlanUmracoTest/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AlanUmracoTest/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AlanUmracoTest/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AlanUmracoTest/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }
        
        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AlanUmracoTest/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AlanUmracoTest/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@Html.Raw(Model.value)

AlanUmracoTest/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>

@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AlanUmracoTest/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AlanUmracoTest/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AlanUmracoTest/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    
    markup = markup.Replace("#value#", umbracoHelper.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode(Model.value.ToString())));
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

AlanUmracoTest/Views/Partials/Home/_Intro.cshtml
<div id="main">
    <div class="shell">
        <div class="col">
            <div class="post">
                <h3>Please click <a href="/chequelist/"><span>HERE</span></a> to go to the cheque list page.</h3>
            </div>
            <div class="post">
                <h3>You can go to the Umbraco login page by clicking <a href="~/Umbraco/"><span>HERE</span></a></h3>
                <p>The credentials required for login have been provided in "How To Run The Test" PDF</p>
            </div>
        </div>
        <div class="cl">&nbsp;</div>
    </div>
</div>

AlanUmracoTest/Views/Partials/SiteLayout/_Footer.cshtml
<footer>
    <div class="footer">
        <div class="shell">
            <p class="lf">Umbraco test done by Alan Kalhor</a></p>
            <p class="rf">Email: <a href="mailto:Alan.Kalhor@gmail.com">Alan.Kalhor@gmail.com</a><a href="http://au.linkedin.com/in/alankalhor" target="_blank"> -  Linkedin: Alan Kalhor</a></p>
            <div style="clear:both;"></div>
        </div>
    </div>
</footer>

AlanUmracoTest/Views/Partials/SiteLayout/_Header.cshtml
<div id="header">
    <div class="shell">
        <div id="navigation">
            <ul>
                <li><a href="/"><span>Home</span></a></li>
                <li><a href="/chequelist/"><span>Cheque List</span></a></li>
                <li><a href="/Umbraco/"><span>Umbraco</span></a></li>
            </ul>
        </div>
        <div class="cl">&nbsp;</div>
    </div>
</div>
<div id="featured-content">
    <div class="shell">
        <h2>Umbraco test done by Alan</h2>
    </div>
</div>

AlanUmracoTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AlanUmracoTest/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Alan Umbraco Test</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="/css/style.css" type="text/css" media="all" />
    <!--[if IE 6]><link rel="stylesheet" href="css/ie6.css" type="text/css" media="all" /><![endif]-->
</head>
<body>
    @{Html.RenderAction("RenderHeader", "SiteLayout");}

    @RenderBody()


    @{Html.RenderAction("RenderFooter", "SiteLayout"); }


</body>
</html>